steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$REPO_NAME'
  - '--imag 1 e'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$REPO_NAME:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY  # 또는 NONE
  # 또는
  logs_bucket: gs://my-logs-bucket # 빌드 로그를 저장할 Cloud Storage 버킷 이름
